// 【重要】このファイルは単語データ専用です
const vocabulary = [
    {id:1,en:"implement",ja:"実行する、導入する",ex:"The company will implement a new policy."},
    {id:2,en:"agenda",ja:"議題",ex:"Let's discuss the next item on the agenda."},
    {id:3,en:"expedite",ja:"早める、促進する",ex:"We need to expedite the delivery process."},
    {id:4,en:"comprehensive",ja:"包括的な",ex:"The report provides a comprehensive review."},
    {id:5,en:"mandatory",ja:"義務的な、必須の",ex:"Attendance is mandatory for all staff."},
    {id:6,en:"remittance",ja:"送金",ex:"Please confirm the remittance details."},
    {id:7,en:"venue",ja:"会場",ex:"The hotel is the venue for the seminar."},
    {id:8,en:"negotiate",ja:"交渉する",ex:"We are ready to negotiate the contract terms."},
    {id:9,en:"reimburse",ja:"払い戻す",ex:"We will reimburse your travel expenses."},
    {id:10,en:"compliance",ja:"遵守",ex:"Safety compliance is strictly monitored."},
    {id:11,en:"curtail",ja:"削減する",ex:"The budget was curtailed significantly."},
    {id:12,en:"deficit",ja:"赤字",ex:"The company reported a budget deficit."},
    {id:13,en:"endorse",ja:"承認する、支持する",ex:"The board voted to endorse the proposal."},
    {id:14,en:"feasible",ja:"実行可能な",ex:"The project is no longer feasible."},
    {id:15,en:"fluctuate",ja:"変動する",ex:"Stock prices fluctuate daily."},
    {id:16,en:"incentive",ja:"動機、報奨金",ex:"Performance incentives are offered to employees."},
    {id:17,en:"liability",ja:"負債、法的責任",ex:"The firm admitted liability for the leak."},
    {id:18,en:"outsource",ja:"外注する",ex:"They decided to outsource their IT support."},
    {id:19,en:"precaution",ja:"予防策",ex:"Take every precaution to avoid errors."},
    {id:20,en:"prospective",ja:"見込みのある",ex:"We are meeting prospective buyers today."},
    {id:21,en:"reluctant",ja:"気が進まない",ex:"He was reluctant to sign the agreement."},
    {id:22,en:"scrutinize",ja:"精査する",ex:"Auditors will scrutinize the accounts."},
    {id:23,en:"unanimous",ja:"全員一致の",ex:"The committee reached a unanimous decision."},
    {id:24,en:"versatile",ja:"多才な",ex:"This software is extremely versatile."},
    {id:25,en:"candidate",ja:"候補者",ex:"She is the strongest candidate for the position."},
    {id:26,en:"specifications",ja:"仕様、詳細",ex:"Read the technical specifications carefully."},
    {id:27,en:"temporary",ja:"一時的な",ex:"This is only a temporary assignment."},
    {id:28,en:"inventory",ja:"在庫",ex:"We conduct inventory checks monthly."},
    {id:29,en:"authorization",ja:"許可、承認",ex:"You need authorization to enter this zone."},
    {id:30,en:"subsidiary",ja:"子会社",ex:"The company has a subsidiary in France."},
    {id:31,en:"commence",ja:"始まる",ex:"The renovation will commence next Monday."},
    {id:32,en:"delegate",ja:"委任する",ex:"Managers should delegate tasks effectively."},
    {id:33,en:"eliminate",ja:"排除する",ex:"We must eliminate unnecessary costs."},
    {id:34,en:"fluency",ja:"流暢さ",ex:"Fluency in English is a requirement."},
    {id:35,en:"gratuitous",ja:"無料の",ex:"The service was gratuitous for members."},
    {id:36,en:"hazard",ja:"危険",ex:"This chemical is a health hazard."},
    {id:37,en:"incorporate",ja:"組み込む",ex:"Try to incorporate feedback into your work."},
    {id:38,en:"justification",ja:"正当化",ex:"There is no justification for the delay."},
    {id:39,en:"knowledgeable",ja:"知識が豊富な",ex:"He is very knowledgeable about local laws."},
    {id:40,en:"legitimate",ja:"合法的な",ex:"It is a legitimate business expense."},
    {id:41,en:"maintenance",ja:"保守、維持",ex:"The machine requires regular maintenance."},
    {id:42,en:"noteworthy",ja:"注目すべき",ex:"There are several noteworthy changes."},
    {id:43,en:"occupant",ja:"居住者",ex:"The previous occupant moved out in May."},
    {id:44,en:"premise",ja:"敷地、前提",ex:"No smoking is allowed on the premises."},
    {id:45,en:"quote",ja:"見積もり",ex:"Can you provide a quote for the repairs?"},
    {id:46,en:"reciprocal",ja:"相互の",ex:"The two countries signed a reciprocal deal."},
    {id:47,en:"stagnant",ja:"停滞した",ex:"The economy has been stagnant for years."},
    {id:48,en:"terminate",ja:"終わらせる",ex:"They decided to terminate the contract."},
    {id:49,en:"utilize",ja:"利用する",ex:"We should utilize all available resources."},
    {id:50,en:"vacant",ja:"空いている",ex:"Are there any vacant seats on the bus?"},
    {id:51,en:"warehouse",ja:"倉庫",ex:"The goods are stored in a large warehouse."},
    {id:52,en:"yield",ja:"産出する、収益",ex:"The investment will yield high returns."},
    {id:53,en:"abbreviate",ja:"短縮する",ex:"Information Technology is often abbreviated as IT."},
    {id:54,en:"behalf",ja:"〜に代わって",ex:"I am writing on behalf of my manager."},
    {id:55,en:"consecutive",ja:"連続した",ex:"Profit rose for three consecutive quarters."},
    {id:56,en:"designated",ja:"指定された",ex:"Please park in the designated area."},
    {id:57,en:"exclusive",ja:"独占的な",ex:"The hotel offers exclusive access to the spa."},
    {id:58,en:"facilitate",ja:"促進する",ex:"Modern tools facilitate communication."},
    {id:59,en:"garment",ja:"衣服",ex:"Dry cleaning is recommended for this garment."},
    {id:60,en:"hostile",ja:"敵対的な",ex:"The firm survived a hostile takeover bid."},
    {id:61,en:"inferior",ja:"劣った",ex:"The quality of this model is inferior to others."},
    {id:62,en:"itinerary",ja:"旅行日程",ex:"Please send me your travel itinerary."},
    {id:63,en:"lucrative",ja:"利益の上がる",ex:"Real estate can be a lucrative business."},
    {id:64,en:"merger",ja:"合併",ex:"The merger of the two giants was approved."},
    {id:65,en:"negligible",ja:"無視できるほどの",ex:"The risk of failure is negligible."},
    {id:66,en:"on-site",ja:"現地での",ex:"We have an on-site cafeteria for staff."},
    {id:67,en:"pertain",ja:"関連する",ex:"These rules pertain to all employees."},
    {id:68,en:"quota",ja:"割り当て",ex:"Each agent has a monthly sales quota."},
    {id:69,en:"reliable",ja:"信頼できる",ex:"We need a reliable supplier for parts."},
    {id:70,en:"supervise",ja:"監督する",ex:"She was hired to supervise the project."},
    {id:71,en:"unprecedented",ja:"前例のない",ex:"The demand for the product is unprecedented."},
    {id:72,en:"vibrant",ja:"活気のある",ex:"The city has a vibrant business district."},
    {id:73,en:"wholesale",ja:"卸売りの",ex:"We buy our supplies at wholesale prices."},
    {id:74,en:"accrue",ja:"生じる",ex:"Interest will accrue on your balance monthly."},
    {id:75,en:"brokerage",ja:"仲介業務",ex:"He works at a major brokerage firm."},
    {id:76,en:"collateral",ja:"担保",ex:"He used his house as collateral for the loan."},
    {id:77,en:"depreciation",ja:"価値の下落",ex:"Car depreciation is fastest in the first year."},
    {id:78,en:"equity",ja:"自己資本",ex:"She built up significant equity in her home."},
    {id:79,en:"forfeit",ja:"没収される",ex:"You will forfeit your deposit if you cancel."},
    {id:80,en:"gross",ja:"総計の",ex:"The company's gross profit exceeded $1 million."},
    {id:81,en:"insolvent",ja:"支払不能の",ex:"Several small shops became insolvent."},
    {id:82,en:"jurisdiction",ja:"管轄権",ex:"The matter is outside our jurisdiction."},
    {id:83,en:"keen",ja:"鋭い、熱心な",ex:"She has a keen interest in marketing."},
    {id:84,en:"lapse",ja:"経過、失効",ex:"His insurance policy was allowed to lapse."},
    {id:85,en:"mortgage",ja:"住宅ローン",ex:"The couple took out a 30-year mortgage."},
    {id:86,en:"nominal",ja:"名目上の",ex:"There is only a nominal fee for the service."},
    {id:87,en:"obsolete",ja:"時代遅れの",ex:"CD players are becoming obsolete."},
    {id:88,en:"portfolio",ja:"作品集、投資構成",ex:"Investors are diversifying their portfolios."},
    {id:89,en:"quorum",ja:"定足数",ex:"We can't start the meeting without a quorum."},
    {id:90,en:"ratify",ja:"批准する",ex:"The parliament is expected to ratify the treaty."},
    {id:91,en:"solvency",ja:"支払い能力",ex:"The bank's solvency is being questioned."},
    {id:92,en:"transaction",ja:"取引",ex:"The online transaction was successful."},
    {id:93,en:"underwrite",ja:"引き受ける",ex:"Several banks agreed to underwrite the loan."},
    {id:94,en:"validate",ja:"有効にする",ex:"Please validate your parking ticket."},
    {id:95,en:"warranty",ja:"保証",ex:"The laptop comes with a two-year warranty."},
    {id:96,en:"yield",ja:"産出する",ex:"Government bonds yield 3% interest."},
    {id:97,en:"zoning",ja:"地域指定",ex:"The zoning laws prohibit tall buildings here."},
    {id:98,en:"affiliate",ja:"提携する",ex:"The university is affiliated with the hospital."},
    {id:99,en:"benchmark",ja:"基準",ex:"This model is the benchmark for performance."},
    {id:100,en:"consolidate",ja:"統合する",ex:"We will consolidate our offices into one."},
    {id:101,en:"briefing",ja:"状況説明",ex:"The staff attended a safety briefing."},
    {id:102,en:"commute",ja:"通勤する",ex:"He has a long commute to the city."},
    {id:103,en:"drastic",ja:"劇的な",ex:"We need to make a drastic change."},
    {id:104,en:"eligible",ja:"資格がある",ex:"You are eligible for a promotion."},
    {id:105,en:"fluctuation",ja:"変動",ex:"We noticed a fluctuation in temperature."},
    {id:106,en:"gratitude",ja:"感謝",ex:"We would like to express our gratitude."},
    {id:107,en:"hygiene",ja:"衛生",ex:"Food hygiene is very important."},
    {id:108,en:"itinerary",ja:"旅行日程",ex:"Please send me your travel itinerary."},
    {id:109,en:"jeopardize",ja:"危険にさらす",ex:"Don't jeopardize your health for work."},
    {id:110,en:"kinship",ja:"親近感",ex:"I felt a kinship with my colleagues."},
    {id:111,en:"lucrative",ja:"利益の上がる",ex:"Real estate can be a lucrative business."},
    {id:112,en:"modest",ja:"控えめな",ex:"He is modest about his success."},
    {id:113,en:"noteworthy",ja:"注目すべき",ex:"There are several noteworthy changes."},
    {id:114,en:"occupant",ja:"居住者",ex:"The previous occupant moved out in May."},
    {id:115,en:"premise",ja:"敷地、前提",ex:"No smoking is allowed on the premises."},
    {id:116,en:"quote",ja:"見積もり",ex:"Can you provide a quote for the repairs?"},
    {id:117,en:"reciprocal",ja:"相互の",ex:"The two countries signed a trade deal."},
    {id:118,en:"stagnant",ja:"停滞した",ex:"The economy has been stagnant for years."},
    {id:119,en:"terminate",ja:"終わらせる",ex:"They decided to terminate the contract."},
    {id:120,en:"utilize",ja:"利用する",ex:"We should utilize all resources."},
    {id:121,en:"abundant",ja:"豊富な",ex:"The region is abundant in natural resources."},
    {id:122,en:"adjourn",ja:"中断する",ex:"The chairperson decided to adjourn the meeting."},
    {id:123,en:"adverse",ja:"有害な",ex:"The project was delayed by adverse weather."},
    {id:124,en:"allocate",ja:"割り当てる",ex:"The company will allocate funds for research."},
    {id:125,en:"approximate",ja:"およその",ex:"What is the approximate cost of the project?"},
    {id:126,en:"arbitrary",ja:"独断的な",ex:"The decision was seen as arbitrary."},
    {id:127,en:"ascertain",ja:"確かめる",ex:"Please ascertain the cause of the failure."},
    {id:128,en:"asset",ja:"資産、強み",ex:"Her ability to lead is a great asset."},
    {id:129,en:"attain",ja:"達成する",ex:"We strive to attain the highest standards."},
    {id:130,en:"audit",ja:"監査",ex:"The firm underwent an internal audit."},
    {id:131,en:"beverage",ja:"飲料",ex:"Complimentary beverages are served on board."},
    {id:132,en:"bid",ja:"入札",ex:"The company won the bid for the bridge."},
    {id:133,en:"boundary",ja:"境界",ex:"The river forms the boundary between the states."},
    {id:134,en:"breach",ja:"違反",ex:"They were sued for breach of contract."},
    {id:135,en:"brochure",ja:"パンフレット",ex:"The brochure contains all the details."},
    {id:136,en:"caption",ja:"説明文",ex:"Please write a caption for the photo."},
    {id:137,en:"cargo",ja:"貨物",ex:"The cargo was unloaded at the port."},
    {id:138,en:"casualty",ja:"犠牲者",ex:"There were no casualties in the accident."},
    {id:139,en:"catalog",ja:"目録",ex:"You can find the items in our spring catalog."},
    {id:140,en:"cater",ja:"料理を賄う",ex:"We cater for all types of events."},
    {id:141,en:"clerical",ja:"事務の",ex:"She is looking for a clerical position."},
    {id:142,en:"closure",ja:"閉鎖",ex:"The road closure caused heavy traffic."},
    {id:143,en:"cohesion",ja:"団結、結束",ex:"Team cohesion is vital for success."},
    {id:144,en:"coincide",ja:"同時に起こる",ex:"My vacation coincides with the conference."},
    {id:145,en:"collaboration",ja:"協力",ex:"The project is a collaboration between firms."},
    {id:146,en:"commodity",ja:"商品",ex:"Oil is a vital global commodity."},
    {id:147,en:"comparable",ja:"同等の",ex:"The two models are comparable in price."},
    {id:148,en:"competent",ja:"有能な",ex:"He is a highly competent manager."},
    {id:149,en:"compliment",ja:"褒め言葉",ex:"I received many compliments on my speech."},
    {id:150,en:"comply",ja:"従う",ex:"You must comply with the regulations."},
    {id:151,en:"concede",ja:"認める",ex:"The candidate had to concede defeat."},
    {id:152,en:"confidential",ja:"機密の",ex:"Keep this information strictly confidential."},
    {id:153,en:"conform",ja:"合わせる",ex:"Products must conform to safety standards."},
    {id:154,en:"congestion",ja:"渋滞、混雑",ex:"Traffic congestion is a problem in the city."},
    {id:155,en:"consent",ja:"同意",ex:"We need your written consent to proceed."},
    {id:156,en:"consultation",ja:"相談、協議",ex:"The plan was decided after consultation."},
    {id:157,en:"controversial",ja:"物議を醸す",ex:"The new law is highly controversial."},
    {id:158,en:"convene",ja:"招集する",ex:"The committee will convene next month."},
    {id:159,en:"correspondence",ja:"通信",ex:"I have a lot of correspondence to deal with."},
    {id:160,en:"counterfeit",ja:"偽造の",ex:"The shop was selling counterfeit goods."},
    {id:161,en:"credential",ja:"資格",ex:"She has impressive academic credentials."},
    {id:162,en:"criterion",ja:"基準",ex:"Success is the main criterion for the award."},
    {id:163,en:"crucial",ja:"極めて重要な",ex:"The meeting is crucial for our future."},
    {id:164,en:"curriculum",ja:"カリキュラム",ex:"The school is revising its curriculum."},
    {id:165,en:"deadline",ja:"締め切り",ex:"The deadline for applications is Friday."},
    {id:166,en:"debris",ja:"残骸、ゴミ",ex:"The street was covered with debris."},
    {id:167,en:"deduct",ja:"差し引く",ex:"Tax will be deducted from your salary."},
    {id:168,en:"defect",ja:"欠陥",ex:"The product was recalled due to a defect."},
    {id:169,en:"defer",ja:"延期する",ex:"They decided to defer the decision."},
    {id:170,en:"defiance",ja:"反抗",ex:"He acted in defiance of the rules."},
    {id:171,en:"delegation",ja:"代表団",ex:"A delegation was sent to the conference."},
    {id:172,en:"deliberate",ja:"故意の",ex:"The move was a deliberate attempt to win."},
    {id:173,en:"demolish",ja:"取り壊す",ex:"The old building will be demolished."},
    {id:174,en:"denounce",ja:"非難する",ex:"The group denounced the government's plan."},
    {id:175,en:"depict",ja:"描く",ex:"The mural depicts a famous battle."},
    {id:176,en:"deprive",ja:"奪う",ex:"The law will deprive citizens of their rights."},
    {id:177,en:"deteriorate",ja:"悪化する",ex:"The weather is expected to deteriorate."},
    {id:178,en:"deviate",ja:"逸脱する",ex:"Do not deviate from the original plan."},
    {id:179,en:"dimension",ja:"寸法",ex:"We need the dimensions of the room."},
    {id:180,en:"discriminate",ja:"差別する",ex:"The law forbids discrimination."},
    {id:181,en:"disrupt",ja:"中断させる",ex:"Heavy snow disrupted the train service."},
    {id:182,en:"distinct",ja:"明確に異なる",ex:"The two concepts are quite distinct."},
    {id:183,en:"divert",ja:"そらす",ex:"Traffic was diverted due to the accident."},
    {id:184,en:"dividend",ja:"配当金",ex:"The company paid a dividend to shareholders."},
    {id:185,en:"doctrine",ja:"主義",ex:"The military doctrine has been updated."},
    {id:186,en:"domestic",ja:"国内の",ex:"The flight is from the domestic terminal."},
    {id:187,en:"drastic",ja:"徹底的な",ex:"The firm made drastic cuts in spending."},
    {id:188,en:"duplicate",ja:"複製する",ex:"Please duplicate this report for me."},
    {id:189,en:"durable",ja:"耐久性のある",ex:"The fabric is very durable."},
    {id:190,en:"dwelling",ja:"住居",ex:"The forest is the dwelling of many animals."},
    {id:191,en:"elaborate",ja:"精巧な",ex:"She made an elaborate plan for the party."},
    {id:192,en:"elevation",ja:"標高",ex:"The city is at a high elevation."},
    {id:193,en:"eligible",ja:"資格がある",ex:"You are eligible for a discount."},
    {id:194,en:"eloquent",ja:"雄弁な",ex:"He gave an eloquent speech at the wedding."},
    {id:195,en:"embark",ja:"乗り出す",ex:"The firm is about to embark on a new venture."},
    {id:196,en:"eminent",ja:"著名な",ex:"The conference was attended by eminent scientists."},
    {id:197,en:"emphasize",ja:"強調する",ex:"I want to emphasize the importance of safety."},
    {id:198,en:"enact",ja:"制定する",ex:"The government is expected to enact the law."},
    {id:199,en:"enforce",ja:"執行する",ex:"The police enforce the law."},
    {id:200,en:"enlighten",ja:"啓発する",ex:"Could you enlighten me on this matter?"},{id:201,en:"anticipate",ja:"予想する、期待する",ex:"We anticipate a large crowd at the event."},
    {id:202,en:"ascertain",ja:"確かめる、突き止める",ex:"Please ascertain the cause of the technical failure."},
    {id:203,en:"collaborate",ja:"協力する、共同で行う",ex:"The two departments will collaborate on the project."},
    {id:204,en:"contradict",ja:"矛盾する、否定する",ex:"The witness's statement seems to contradict the evidence."},
    {id:205,en:"cultivate",ja:"育てる、耕す、磨く",ex:"The seminar helps employees cultivate leadership skills."},
    {id:206,en:"deteriorate",ja:"悪化する",ex:"The weather is expected to deteriorate by evening."},
    {id:207,en:"diminish",ja:"減少する、衰える",ex:"Our resources are beginning to diminish."},
    {id:208,en:"disseminate",ja:"普及させる、広める",ex:"The information was disseminated via the company intranet."},
    {id:209,en:"eliminate",ja:"排除する、取り除く",ex:"The new system will eliminate unnecessary paperwork."},
    {id:210,en:"emphasize",ja:"強調する",ex:"I want to emphasize the importance of data security."},
    {id:211,en:"encounter",ja:"遭遇する",ex:"We might encounter some problems during the transition."},
    {id:212,en:"enhance",ja:"高める、強化する",ex:"The upgrade will enhance the performance of the software."},
    {id:213,en:"ensure",ja:"確実にする、保証する",ex:"Please ensure that all windows are locked."},
    {id:214,en:"evaluate",ja:"評価する",ex:"The manager will evaluate your performance next week."},
    {id:215,en:"exhibit",ja:"展示する、示す",ex:"The artist will exhibit her work at the gallery."},
    {id:216,en:"facilitate",ja:"促進する、容易にする",ex:"Modern technology helps facilitate global communication."},
    {id:217,en:"fluctuate",ja:"変動する",ex:"Oil prices continue to fluctuate significantly."},
    {id:218,en:"generate",ja:"生み出す、発生させる",ex:"The new marketing campaign generated a lot of leads."},
    {id:219,en:"implement",ja:"実行する、導入する",ex:"We need to implement the new safety regulations immediately."},
    {id:220,en:"incorporate",ja:"組み込む、合併する",ex:"We decided to incorporate your suggestions into the final plan."},
    {id:221,en:"indicate",ja:"示す、指し示す",ex:"The survey results indicate a high level of satisfaction."},
    {id:222,en:"inspect",ja:"検査する、点検する",ex:"A technician will come to inspect the elevator today."},
    {id:223,en:"interpret",ja:"解釈する、通訳する",ex:"How should we interpret the recent market trends?"},
    {id:224,en:"investigate",ja:"調査する",ex:"The police are investigating the cause of the accident."},
    {id:225,en:"justify",ja:"正当化する",ex:"It is hard to justify the high cost of this equipment."},
    {id:226,en:"maintain",ja:"維持する、整備する",ex:"You should maintain a healthy work-life balance."},
    {id:227,en:"modify",ja:"修正する、変更する",ex:"We may need to modify the design to meet the client's needs."},
    {id:228,en:"monitor",ja:"監視する",ex:"The system will monitor the temperature in the server room."},
    {id:229,en:"negotiate",ja:"交渉する",ex:"The union is trying to negotiate a better deal for workers."},
    {id:230,en:"notify",ja:"通知する",ex:"Please notify us if your contact information changes."},
    {id:231,en:"obtain",ja:"手に入れる、獲得する",ex:"You can obtain a visa at the embassy."},
    {id:232,en:"occupy",ja:"占める、占有する",ex:"The administrative offices occupy the third floor."},
    {id:233,en:"participate",ja:"参加する",ex:"Everyone is encouraged to participate in the discussion."},
    {id:234,en:"perceive",ja:"認識する、気づく",ex:"Many people perceive him to be a strong leader."},
    {id:235,en:"postpone",ja:"延期する",ex:"The meeting has been postponed until next Friday."},
    {id:236,en:"predict",ja:"予測する",ex:"It is difficult to predict the outcome of the election."},
    {id:237,en:"prohibit",ja:"禁止する",ex:"Smoking is strictly prohibited inside the building."},
    {id:238,en:"promote",ja:"促進する、昇進させる",ex:"The company aims to promote diversity in the workplace."},
    {id:239,en:"pursue",ja:"追求する、続ける",ex:"She decided to pursue a career in international law."},
    {id:240,en:"reconcile",ja:"和解させる、一致させる",ex:"It's hard to reconcile these two conflicting reports."},
    {id:241,en:"reduce",ja:"減らす",ex:"The goal is to reduce energy consumption by 20%."},
    {id:242,en:"reflect",ja:"反映する、熟考する",ex:"The budget reflects our commitment to innovation."},
    {id:243,en:"register",ja:"登録する",ex:"You need to register online to attend the workshop."},
    {id:244,en:"regulate",ja:"規制する、調整する",ex:"The government plans to regulate the use of drones."},
    {id:245,en:"reinforce",ja:"強化する",ex:"The evidence serves to reinforce our original theory."},
    {id:246,en:"relocate",ja:"移転する",ex:"The head office will relocate to London next year."},
    {id:247,en:"require",ja:"必要とする",ex:"The job requires excellent communication skills."},
    {id:248,en:"resolve",ja:"解決する",ex:"We are working hard to resolve the customer's complaint."},
    {id:249,en:"respond",ja:"返答する、反応する",ex:"How did the audience respond to the presentation?"},
    {id:250,en:"retain",ja:"保持する、忘れない",ex:"The company aims to retain its top talent."},
    {id:251,en:"reveal",ja:"明らかにする",ex:"The study revealed a surprising link between the two events."},
    {id:252,en:"scrutinize",ja:"精査する",ex:"The committee will scrutinize the financial records."},
    {id:253,en:"specify",ja:"明記する、特定する",ex:"Please specify which model you would like to order."},
    {id:254,en:"submit",ja:"提出する",ex:"You must submit your expense report by Friday."},
    {id:255,en:"substitute",ja:"代用する",ex:"You can substitute honey for sugar in this recipe."},
    {id:256,en:"sustain",ja:"維持する、支える",ex:"The economy needs a boost to sustain growth."},
    {id:257,en:"terminate",ja:"終わらせる",ex:"The contract will terminate at the end of the month."},
    {id:258,en:"undergo",ja:"経験する、受ける",ex:"The building is currently undergoing renovation."},
    {id:259,en:"undertake",ja:"引き受ける、着手する",ex:"The firm will undertake a major research project."},
    {id:260,en:"utilize",ja:"利用する、活用する",ex:"We should utilize all available marketing channels."},
    {id:261,en:"validate",ja:"有効にする、確認する",ex:"Don't forget to validate your parking ticket."},
    {id:262,en:"verify",ja:"確認する、証明する",ex:"Please verify your identity with a passport or ID card."},
    {id:263,en:"withdraw",ja:"撤退する、引き出す",ex:"The company decided to withdraw from the Russian market."},
    {id:264,en:"yield",ja:"産出する、屈する",ex:"The investment is expected to yield significant profits."},
    {id:265,en:"abandon",ja:"諦める、捨てる",ex:"The project was abandoned due to a lack of funding."},
    {id:266,en:"abolish",ja:"廃止する",ex:"Many countries have abolished the death penalty."},
    {id:267,en:"accommodate",ja:"収容する、適応させる",ex:"The hotel can accommodate up to 500 guests."},
    {id:268,en:"accompany",ja:"同行する、添える",ex:"Children must be accompanied by an adult."},
    {id:269,en:"accomplish",ja:"成し遂げる",ex:"We can accomplish anything if we work together."},
    {id:270,en:"accumulate",ja:"蓄積する",ex:"Dust tends to accumulate under the bed."},
    {id:271,en:"accuse",ja:"非難する、告訴する",ex:"He was accused of leaking confidential information."},
    {id:272,en:"acknowledge",ja:"認める、受領を知らせる",ex:"Please acknowledge receipt of this email."},
    {id:273,en:"acquire",ja:"習得する、買収する",ex:"The company recently acquired a small tech startup."},
    {id:274,en:"adapt",ja:"適応させる、作り直す",ex:"It takes time to adapt to a new culture."},
    {id:275,en:"adjust",ja:"調整する、慣れる",ex:"You can adjust the seat height for your comfort."},
    {id:276,en:"administer",ja:"管理する、運営する",ex:"The fund is administered by a board of trustees."},
    {id:277,en:"advocate",ja:"提唱する、主張する",ex:"She advocates for environmental protection."},
    {id:278,en:"affect",ja:"影響を与える",ex:"The new tax law will affect small businesses."},
    {id:279,en:"allocate",ja:"割り当てる",ex:"The government will allocate more money to education."},
    {id:280,en:"alter",ja:"変える、作り直す",ex:"We had to alter our travel plans at the last minute."},
    {id:281,en:"amend",ja:"修正する、改正する",ex:"The committee voted to amend the bylaws."},
    {id:282,en:"analyze",ja:"分析する",ex:"We need to analyze the sales data more carefully."},
    {id:283,en:"announce",ja:"発表する",ex:"The company will announce its quarterly results tomorrow."},
    {id:284,en:"apply",ja:"申し込む、適用する",ex:"You can apply for the position online."},
    {id:285,en:"appoint",ja:"任命する、指定する",ex:"He was appointed as the new CEO last month."},
    {id:286,en:"appreciate",ja:"感謝する、高く評価する",ex:"I really appreciate your help with this project."},
    {id:287,en:"approach",ja:"近づく、取り組む",ex:"We need to find a new approach to the problem."},
    {id:288,en:"approve",ja:"承認する",ex:"The board of directors approved the merger."},
    {id:289,en:"arrange",ja:"手配する、並べる",ex:"I'll arrange a meeting with the client for Tuesday."},
    {id:290,en:"assemble",ja:"組み立てる、集める",ex:"The parts are easy to assemble with simple tools."},
    {id:291,en:"assess",ja:"評価する、査定する",ex:"The consultant will assess the risk of the project."},
    {id:292,en:"assign",ja:"割り当てる、配属する",ex:"The teacher will assign a new project to the class."},
    {id:293,en:"assist",ja:"手伝う、助ける",ex:"We are here to assist you with any questions."},
    {id:294,en:"associate",ja:"関連づける、交際する",ex:"Many people associate the brand with quality."},
    {id:295,en:"assume",ja:"仮定する、引き受ける",ex:"He will assume the role of manager in June."},
    {id:296,en:"assure",ja:"確信させる、保証する",ex:"I can assure you that everything will be fine."},
    {id:297,en:"attach",ja:"添付する、取り付ける",ex:"Please attach your resume to the email."},
    {id:298,en:"attain",ja:"達成する、到達する",ex:"She worked hard to attain her goals."},
    {id:299,en:"attempt",ja:"試みる",ex:"The hikers will attempt to reach the summit by noon."},
    {id:300,en:"attend",ja:"出席する、注意を払う",ex:"He plans to attend the conference in Tokyo."},{id:301,en:"attract",ja:"引きつける、魅了する",ex:"The new museum aims to attract more tourists."},
    {id:302,en:"attribute",ja:"〜のせいにする、属性",ex:"She attributes her success to hard work."},
    {id:303,en:"authorize",ja:"権限を与える、公認する",ex:"The manager must authorize any overtime work."},
    {id:304,en:"avoid",ja:"避ける",ex:"Try to avoid making the same mistake twice."},
    {id:305,en:"balance",ja:"均衡、残高",ex:"Please check your account balance regularly."},
    {id:306,en:"ban",ja:"禁止する",ex:"The government plans to ban plastic bags."},
    {id:307,en:"bargain",ja:"買い得品、交渉する",ex:"This laptop was a real bargain."},
    {id:308,en:"base",ja:"根拠、土台",ex:"The company's head office is based in Osaka."},
    {id:309,en:"bear",ja:"耐える、持つ、運ぶ",ex:"The structure can bear a lot of weight."},
    {id:310,en:"beat",ja:"打ち負かす、打つ",ex:"Our team managed to beat the champions."},
    {id:311,en:"become",ja:"〜になる、似合う",ex:"Digital technology has become essential for business."},
    {id:312,en:"begin",ja:"始める",ex:"The ceremony will begin at 10 AM sharp."},
    {id:313,en:"behave",ja:"振る舞う",ex:"He behaved very professionally during the crisis."},
    {id:314,en:"believe",ja:"信じる",ex:"I believe we can meet the deadline."},
    {id:315,en:"belong",ja:"属する",ex:"This umbrella belongs to me."},
    {id:316,en:"bend",ja:"曲げる",ex:"Be careful not to bend the metal rod."},
    {id:317,en:"benefit",ja:"利益を得る、利益",ex:"Many people will benefit from the new law."},
    {id:318,en:"betray",ja:"裏切る、漏らす",ex:"He would never betray his colleagues."},
    {id:319,en:"bid",ja:"入札する、値を付ける",ex:"Three firms bid for the construction project."},
    {id:320,en:"bind",ja:"縛る、拘束する",ex:"The contract binds both parties to the agreement."},
    {id:321,en:"blame",ja:"責める、〜のせいにする",ex:"Don't blame others for your own mistakes."},
    {id:322,en:"block",ja:"塞ぐ、阻止する",ex:"The fallen tree is blocking the road."},
    {id:323,en:"bloom",ja:"花が咲く",ex:"The cherry blossoms will bloom next week."},
    {id:324,en:"board",ja:"乗り込む、会議",ex:"Passengers should board the plane now."},
    {id:325,en:"boast",ja:"自慢する",ex:"The city boasts many historic buildings."},
    {id:326,en:"boost",ja:"高める、押し上げる",ex:"Lower interest rates may boost the economy."},
    {id:327,en:"borrow",ja:"借りる",ex:"Can I borrow your pen for a moment?"},
    {id:328,en:"bother",ja:"悩ませる、困らせる",ex:"I'm sorry to bother you, but I have a question."},
    {id:329,en:"bound",ja:"縛られた、〜行きの",ex:"The train is bound for Tokyo Station."},
    {id:330,en:"brake",ja:"ブレーキをかける",ex:"The driver had to brake suddenly."},
    {id:331,en:"branch",ja:"支店、枝",ex:"Our bank has a branch in every major city."},
    {id:332,en:"break",ja:"壊す、休む",ex:"Let's take a short break after this task."},
    {id:333,en:"breed",ja:"飼育する、繁殖する",ex:"The farmer breeds sheep and cattle."},
    {id:334,en:"bring",ja:"持ってくる",ex:"Please bring your ID to the interview."},
    {id:335,en:"broadcast",ja:"放送する",ex:"The news is broadcast live every evening."},
    {id:336,en:"broaden",ja:"広げる",ex:"Traveling helps broaden your horizons."},
    {id:337,en:"browse",ja:"閲覧する、拾い読みする",ex:"I'm just browsing, thank you."},
    {id:338,en:"build",ja:"建てる、築く",ex:"They plan to build a new factory here."},
    {id:339,en:"burden",ja:"負担、重荷",ex:"The tax increase is a burden on small businesses."},
    {id:340,en:"burn",ja:"燃える",ex:"Wood burns easily when it's dry."},
    {id:341,en:"burst",ja:"破裂する",ex:"The pipe burst due to the freezing weather."},
    {id:342,en:"bury",ja:"埋める、隠す",ex:"The cables are buried deep underground."},
    {id:343,en:"buy",ja:"買う",ex:"I need to buy some office supplies."},
    {id:344,en:"calculate",ja:"計算する",ex:"We need to calculate the total cost."},
    {id:345,en:"call",ja:"呼ぶ、電話する",ex:"I'll call you as soon as I arrive."},
    {id:346,en:"cancel",ja:"取り消す",ex:"The flight was canceled due to bad weather."},
    {id:347,en:"capture",ja:"捕らえる、記録する",ex:"The photographer managed to capture the moment."},
    {id:348,en:"care",ja:"気にする、世話をする",ex:"She really cares about her patients."},
    {id:349,en:"carry",ja:"運ぶ、扱う",ex:"Does this shop carry spare parts?"},
    {id:350,en:"cast",ja:"投げる、投じる",ex:"Don't forget to cast your vote."},
    {id:351,en:"catch",ja:"捕まえる、間に合う",ex:"I need to catch the 8:30 train."},
    {id:352,en:"cause",ja:"引き起こす、原因",ex:"The heavy rain caused a flood."},
    {id:353,en:"cease",ja:"やめる、終わる",ex:"The company will cease operations next month."},
    {id:354,en:"celebrate",ja:"祝う",ex:"We are gathering to celebrate her promotion."},
    {id:355,en:"center",ja:"中心、集中させる",ex:"The discussion centered on the budget."},
    {id:356,en:"certify",ja:"証明する",ex:"The laboratory will certify the results."},
    {id:357,en:"challenge",ja:"挑戦する、疑う",ex:"He decided to challenge the court's decision."},
    {id:358,en:"change",ja:"変える、お釣り",ex:"I need to change some yen into dollars."},
    {id:359,en:"charge",ja:"請求する、充電する",ex:"How much do you charge for delivery?"},
    {id:360,en:"charter",ja:"貸し切る、憲章",ex:"We chartered a bus for the company trip."},
    {id:361,en:"chase",ja:"追いかける",ex:"The cat is chasing a mouse."},
    {id:362,en:"chat",ja:"おしゃべりする",ex:"We had a quick chat about the project."},
    {id:363,en:"check",ja:"確認する、小切手",ex:"Please check the documents for errors."},
    {id:364,en:"cheer",ja:"元気づける、歓声を上げる",ex:"The crowd cheered for the winner."},
    {id:365,en:"choose",ja:"選ぶ",ex:"You can choose from a variety of colors."},
    {id:366,en:"circulate",ja:"循環する、配布する",ex:"Please circulate this memo to all staff."},
    {id:367,en:"cite",ja:"引用する、挙げる",ex:"The report cites several successful cases."},
    {id:368,en:"claim",ja:"主張する、要求する",ex:"You can claim your expenses online."},
    {id:369,en:"clarify",ja:"明確にする",ex:"Could you clarify what you mean by that?"},
    {id:370,en:"classify",ja:"分類する",ex:"The books are classified by subject."},
    {id:371,en:"clean",ja:"掃除する",ex:"Make sure to clean the machine after use."},
    {id:372,en:"clear",ja:"片付ける、晴れる",ex:"Please clear the table after lunch."},
    {id:373,en:"climb",ja:"登る",ex:"The stock market continues to climb."},
    {id:374,en:"close",ja:"閉める、近い",ex:"The shop will close at 9 PM."},
    {id:375,en:"clothe",ja:"服を着せる",ex:"They struggled to clothe and feed their family."},
    {id:376,en:"collect",ja:"集める",ex:"I'll collect the data for the report."},
    {id:377,en:"combine",ja:"組み合わせる",ex:"We should combine our efforts to succeed."},
    {id:378,en:"comfort",ja:"慰める、快適さ",ex:"The new office chairs provide more comfort."},
    {id:379,en:"command",ja:"命令する、操る",ex:"He has a good command of English."},
    {id:380,en:"commemorate",ja:"記念する",ex:"The plaque commemorates the building's history."},
    {id:381,en:"commence",ja:"始まる、開始する",ex:"The ceremony will commence shortly."},
    {id:382,en:"commend",ja:"褒める、推奨する",ex:"The manager commended him for his hard work."},
    {id:383,en:"comment",ja:"意見を述べる",ex:"The spokesperson refused to comment."},
    {id:384,en:"commit",ja:"約束する、犯す",ex:"We are committed to providing quality service."},
    {id:385,en:"communicate",ja:"伝える、意思疎通する",ex:"It's important to communicate clearly."},
    {id:386,en:"compare",ja:"比較する",ex:"Compare the prices before you buy."},
    {id:387,en:"compel",ja:"強制する",ex:"The law compels companies to pay tax."},
    {id:388,en:"compensate",ja:"補償する",ex:"We will compensate you for the delay."},
    {id:389,en:"compete",ja:"競争する",ex:"Many firms compete in the global market."},
    {id:390,en:"compile",ja:"まとめる、編集する",ex:"We are compiling a list of potential clients."},
    {id:391,en:"complain",ja:"不平を言う",ex:"Customers often complain about the noise."},
    {id:392,en:"complete",ja:"完成させる",ex:"You must complete the form in ink."},
    {id:393,en:"complicate",ja:"複雑にする",ex:"Let's not complicate the situation further."},
    {id:394,en:"compliment",ja:"褒める、お世辞",ex:"She complimented me on my presentation."},
    {id:395,en:"comply",ja:"従う、遵守する",ex:"All products must comply with safety standards."},
    {id:396,en:"compose",ja:"構成する、書く",ex:"The committee is composed of five members."},
    {id:397,en:"comprise",ja:"含む、〜から成る",ex:"The package comprises a hotel and flights."},
    {id:398,en:"compromise",ja:"妥協する、汚す",ex:"We had to compromise on the final price."},
    {id:399,en:"compute",ja:"計算する",ex:"The computer can compute large amounts of data."},
    {id:400,en:"conceal",ja:"隠す",ex:"He tried to conceal his disappointment."},
    {id:401,en:"concede",ja:"認める、譲歩する",ex:"The candidate had to concede defeat."},
    {id:402,en:"conceive",ja:"思いつく、想像する",ex:"It's hard to conceive of such a situation."},
    {id:403,en:"concentrate",ja:"集中する",ex:"I need a quiet place to concentrate."},
    {id:404,en:"concern",ja:"心配させる、関わる",ex:"The report concerns the future of the company."},
    {id:405,en:"conclude",ja:"結論づける、終える",ex:"We concluded the meeting with a summary."},
    {id:406,en:"condemn",ja:"非難する",ex:"The local community condemned the plan."},
    {id:407,en:"conduct",ja:"行う、実施する",ex:"The firm will conduct a market survey."},
    {id:408,en:"confer",ja:"協議する、授与する",ex:"The degree was conferred at the ceremony."},
    {id:409,en:"confess",ja:"告白する、認める",ex:"He confessed to making a mistake."},
    {id:410,en:"confide",ja:"信頼する、打ち明ける",ex:"She confided her secrets to her best friend."},
    {id:411,en:"confine",ja:"制限する、閉じ込める",ex:"Please confine your remarks to the topic."},
    {id:412,en:"confirm",ja:"確認する",ex:"I'd like to confirm my reservation."},
    {id:413,en:"conflict",ja:"衝突する、矛盾する",ex:"The two reports conflict with each other."},
    {id:414,en:"conform",ja:"従う、一致する",ex:"The building must conform to safety codes."},
    {id:415,en:"confront",ja:"直面する、立ち向かう",ex:"We must confront the problem immediately."},
    {id:416,en:"confuse",ja:"混乱させる",ex:"The complex instructions confused the users."},
    {id:417,en:"congratulate",ja:"祝う",ex:"I want to congratulate you on your success."},
    {id:418,en:"connect",ja:"つなぐ",ex:"The printer is connected to the network."},
    {id:419,en:"conquer",ja:"征服する、克服する",ex:"She managed to conquer her fear of flying."},
    {id:420,en:"consent",ja:"同意する",ex:"My parents consented to my studying abroad."},
    {id:421,en:"conserve",ja:"保護する、節約する",ex:"We should conserve energy and water."},
    {id:422,en:"consider",ja:"検討する、見なす",ex:"Please consider our offer carefully."},
    {id:423,en:"consist",ja:"〜から成る",ex:"The team consists of five experts."},
    {id:424,en:"constitute",ja:"構成する、制定する",ex:"This move constitutes a breach of contract."},
    {id:425,en:"construct",ja:"建設する",ex:"They are constructing a new bridge."},
    {id:426,en:"consult",ja:"相談する",ex:"You should consult a lawyer first."},
    {id:427,en:"consume",ja:"消費する",ex:"This car consumes a lot of fuel."},
    {id:428,en:"contact",ja:"連絡する",ex:"Please contact us for more details."},
    {id:429,en:"contain",ja:"含む",ex:"The bottle contains 500ml of water."},
    {id:430,en:"contemplate",ja:"熟考する",ex:"She is contemplating changing her career."},
    {id:431,en:"contend",ja:"主張する、競う",ex:"The company contends that it is not liable."},
    {id:432,en:"continue",ja:"続ける",ex:"The rain will continue until tomorrow."},
    {id:433,en:"contract",ja:"契約する、収縮する",ex:"Metal contracts as it cools."},
    {id:434,en:"contradict",ja:"矛盾する",ex:"His actions contradict his words."},
    {id:435,en:"contrast",ja:"対照させる",ex:"The report contrasts the two systems."},
    {id:436,en:"contribute",ja:"貢献する、寄付する",ex:"Everyone should contribute to the project."},
    {id:437,en:"control",ja:"管理する、制御する",ex:"The pilot managed to control the plane."},
    {id:438,en:"convene",ja:"招集する、集まる",ex:"The committee will convene next week."},
    {id:439,en:"convert",ja:"変える、転換する",ex:"We converted the garage into a studio."},
    {id:440,en:"convey",ja:"伝える、運ぶ",ex:"Colors can convey different meanings."},
    {id:441,en:"convince",ja:"納得させる",ex:"He tried to convince me to join the club."},
    {id:442,en:"cook",ja:"料理する",ex:"I like to cook for my friends."},
    {id:443,en:"cool",ja:"冷やす",ex:"The cake needs to cool before serving."},
    {id:444,en:"cooperate",ja:"協力する",ex:"We need to cooperate with our partners."},
    {id:445,en:"coordinate",ja:"調整する",ex:"The manager will coordinate the event."},
    {id:446,en:"cope",ja:"対処する",ex:"She is learning to cope with stress."},
    {id:447,en:"copy",ja:"複写する、真似る",ex:"Can you copy this document for me?"},
    {id:448,en:"correct",ja:"訂正する、正しい",ex:"Please correct any errors in the text."},
    {id:449,en:"correspond",ja:"一致する、文通する",ex:"The two figures correspond exactly."},
    {id:450,en:"cost",ja:"費用がかかる",ex:"How much does the repair cost?"},
    {id:451,en:"counsel",ja:"助言する",ex:"The lawyer counseled his client to wait."},
    {id:452,en:"count",ja:"数える、重要である",ex:"Every vote counts in the election."},
    {id:453,en:"counter",ja:"対抗する、反対する",ex:"The firm countered the rival's offer."},
    {id:454,en:"cover",ja:"覆う、カバーする",ex:"The insurance covers theft and damage."},
    {id:455,en:"crack",ja:"ひびが入る",ex:"The window cracked during the storm."},
    {id:456,en:"crash",ja:"衝突する、墜落する",ex:"The computer crashed three times today."},
    {id:457,en:"create",ja:"作る、創造する",ex:"We want to create a friendly atmosphere."},
    {id:458,en:"credit",ja:"信じる、〜の功績にする",ex:"He is credited with the discovery."},
    {id:459,en:"criticize",ja:"批判する",ex:"They criticized the government's policy."},
    {id:460,en:"cross",ja:"渡る、交差する",ex:"Be careful when you cross the street."},
    {id:461,en:"crowd",ja:"押し寄せる、群衆",ex:"Fans crowded around the star."},
    {id:462,en:"crush",ja:"押しつぶす",ex:"The boxes were crushed during shipping."},
    {id:463,en:"cry",ja:"泣く、叫ぶ",ex:"The baby started to cry loudly."},
    {id:464,en:"cultivate",ja:"育てる、耕す",ex:"The firm aims to cultivate new markets."},
    {id:465,en:"cure",ja:"治す",ex:"The doctor managed to cure the disease."},
    {id:466,en:"curl",ja:"巻く",ex:"Her hair curls naturally."},
    {id:467,en:"curtail",ja:"削減する",ex:"We had to curtail our travel plans."},
    {id:468,en:"curve",ja:"曲がる",ex:"The road curves to the left here."},
    {id:469,en:"cut",ja:"切る、削減する",ex:"They decided to cut the budget."},
    {id:470,en:"damage",ja:"損害を与える",ex:"The storm damaged several buildings."},
    {id:471,en:"dance",ja:"踊る",ex:"We danced all night at the party."},
    {id:472,en:"dare",ja:"あえて〜する",ex:"I wouldn't dare to ask him that."},
    {id:473,en:"dash",ja:"急いで行く",ex:"He dashed to catch the last train."},
    {id:474,en:"deal",ja:"扱う、配る",ex:"This report deals with environmental issues."},
    {id:475,en:"debate",ja:"討論する",ex:"The MPs debated the new tax bill."},
    {id:476,en:"decide",ja:"決める",ex:"We need to decide on the venue."},
    {id:477,en:"declare",ja:"宣言する、申告する",ex:"Do you have anything to declare?"},
    {id:478,en:"decline",ja:"断る、低下する",ex:"The population is starting to decline."},
    {id:479,en:"decorate",ja:"飾る",ex:"We decorated the hall with balloons."},
    {id:480,en:"decrease",ja:"減る、減らす",ex:"The price has decreased by 10%."},
    {id:481,en:"dedicate",ja:"捧げる",ex:"He dedicated his life to science."},
    {id:482,en:"deem",ja:"見なす",ex:"The area was deemed unsafe for tourists."},
    {id:483,en:"defeat",ja:"負かす",ex:"The team suffered a heavy defeat."},
    {id:484,en:"defend",ja:"守る、弁護する",ex:"The lawyer defended his client well."},
    {id:485,en:"define",ja:"定義する",ex:"How do you define success?"},
    {id:486,en:"defy",ja:"無視する、挑む",ex:"His actions defy explanation."},
    {id:487,en:"delay",ja:"遅らせる",ex:"The flight was delayed by two hours."},
    {id:488,en:"delegate",ja:"委任する、代表",ex:"Managers should delegate tasks to staff."},
    {id:489,en:"delete",ja:"削除する",ex:"Please delete the unnecessary files."},
    {id:490,en:"deliberate",ja:"熟考する、故意の",ex:"The jury is still deliberating."},
    {id:491,en:"delight",ja:"喜ばせる",ex:"The news delighted the whole family."},
    {id:492,en:"deliver",ja:"届ける、行う",ex:"The package was delivered this morning."},
    {id:493,en:"demand",ja:"要求する",ex:"The workers demanded higher wages."},
    {id:494,en:"demonstrate",ja:"実演する、示す",ex:"The technician will demonstrate the new tool."},
    {id:495,en:"denote",ja:"示す、意味する",ex:"A red light denotes danger."},
    {id:496,en:"denounce",ja:"非難する",ex:"The group denounced the government's plan."},
    {id:497,en:"deny",ja:"否定する、拒む",ex:"He denied all the allegations."},
    {id:498,en:"depart",ja:"出発する",ex:"The train is scheduled to depart at 9:00."},
    {id:499,en:"depend",ja:"依存する、〜次第である",ex:"Our success depends on teamwork."},
    {id:500,en:"depict",ja:"描く、描写する",ex:"The film depicts the life of the artist."},{id:501,en:"deploy",ja:"配置する、展開する",ex:"The company plans to deploy the new software next month."},
    {id:502,en:"deposit",ja:"預金する、置く、頭金",ex:"You need to pay a 10% deposit for the car."},
    {id:503,en:"derive",ja:"由来する、引き出す",ex:"Many English words are derived from Latin."},
    {id:504,en:"describe",ja:"描写する、説明する",ex:"Can you describe the man you saw?"},
    {id:505,en:"deserve",ja:"値する",ex:"They deserve to win after all their hard work."},
    {id:506,en:"designate",ja:"指定する",ex:"This area is designated for non-smokers."},
    {id:507,en:"desire",ja:"強く望む",ex:"We all desire a better quality of life."},
    {id:508,en:"destroy",ja:"破壊する",ex:"The fire destroyed most of the building."},
    {id:509,en:"detach",ja:"切り離す",ex:"Please detach the coupon and send it to us."},
    {id:510,en:"detect",ja:"感知する、見つける",ex:"The sensor can detect even small gas leaks."},
    {id:511,en:"deteriorate",ja:"悪化する",ex:"The relationship between the two firms deteriorated."},
    {id:512,en:"determine",ja:"決定する、特定する",ex:"We need to determine the cause of the problem."},
    {id:513,en:"develop",ja:"開発する、発達する",ex:"The team is developing a new mobile app."},
    {id:514,en:"devise",ja:"考案する",ex:"Scientists have devised a new method for testing water."},
    {id:515,en:"devote",ja:"捧げる",ex:"He devoted his life to helping the poor."},
    {id:516,en:"diagnose",ja:"診断する",ex:"The doctor diagnosed him with a rare condition."},
    {id:517,en:"dictate",ja:"書き取らせる、命令する",ex:"The boss dictated a letter to his secretary."},
    {id:518,en:"differ",ja:"異なる",ex:"The two models differ in several ways."},
    {id:519,en:"differentiate",ja:"区別する",ex:"It's hard to differentiate between the two products."},
    {id:520,en:"diffuse",ja:"拡散する",ex:"The scent of flowers diffused through the room."},
    {id:521,en:"digest",ja:"消化する、要約",ex:"It takes time to digest a large meal."},
    {id:522,en:"diminish",ja:"減らす、減少する",ex:"Our resources are starting to diminish."},
    {id:523,en:"direct",ja:"指示する、向ける、直接の",ex:"The signs direct you to the nearest exit."},
    {id:524,en:"disagree",ja:"意見が合わない",ex:"I'm afraid I disagree with your opinion."},
    {id:525,en:"disappear",ja:"消える",ex:"The sun disappeared behind the clouds."},
    {id:526,en:"disappoint",ja:"失望させる",ex:"The team's performance disappointed the fans."},
    {id:527,en:"discard",ja:"捨てる、放棄する",ex:"Please discard any old documents."},
    {id:528,en:"discharge",ja:"放出する、解任する",ex:"The factory was fined for discharging chemicals."},
    {id:529,en:"disclose",ja:"公開する、暴露する",ex:"The company refused to disclose the information."},
    {id:530,en:"disconnect",ja:"切断する",ex:"Make sure to disconnect the power before repairs."},
    {id:531,en:"discount",ja:"割引する",ex:"Students are entitled to a 20% discount."},
    {id:532,en:"discourage",ja:"落胆させる、思いとどまらせる",ex:"Don't let failure discourage you."},
    {id:533,en:"discover",ja:"発見する",ex:"Who discovered America?"},
    {id:534,en:"discriminate",ja:"差別する",ex:"The law forbids companies to discriminate."},
    {id:535,en:"discuss",ja:"話し合う",ex:"We need to discuss the new budget."},
    {id:536,en:"disinfect",ja:"消毒する",ex:"Always disinfect the wound before bandaging it."},
    {id:537,en:"dislike",ja:"嫌う",ex:"Many people dislike working on weekends."},
    {id:538,en:"dismiss",ja:"解雇する、却下する",ex:"The manager dismissed the idea immediately."},
    {id:539,en:"displace",ja:"取って代わる、追放する",ex:"Many workers were displaced by machines."},
    {id:540,en:"display",ja:"展示する、表示する",ex:"The monitor displays the current temperature."},
    {id:541,en:"dispose",ja:"処分する",ex:"Please dispose of your trash properly."},
    {id:542,en:"dispute",ja:"論争する",ex:"The two companies are disputing the contract."},
    {id:543,en:"disregard",ja:"無視する",ex:"Please disregard my previous email."},
    {id:544,en:"disrupt",ja:"中断させる、混乱させる",ex:"Heavy snow disrupted the train service."},
    {id:545,en:"disseminate",ja:"普及させる",ex:"The findings were disseminated through journals."},
    {id:546,en:"dissolve",ja:"溶かす、解消する",ex:"Sugar dissolves easily in hot water."},
    {id:547,en:"distinguish",ja:"見分ける",ex:"He can't distinguish red from green."},
    {id:548,en:"distort",ja:"ゆがめる",ex:"The mirror distorts your reflection."},
    {id:549,en:"distract",ja:"気を散らす",ex:"Please don't distract me while I'm driving."},
    {id:550,en:"distribute",ja:"分配する、配布する",ex:"The flyers were distributed in the city center."},
    {id:551,en:"distrust",ja:"不信感を抱く",ex:"Many voters distrust the government."},
    {id:552,en:"disturb",ja:"邪魔する、かき乱す",ex:"Do not disturb the patients."},
    {id:553,en:"divert",ja:"そらす",ex:"Traffic was diverted because of an accident."},
    {id:554,en:"divide",ja:"分ける",ex:"The profits will be divided among the partners."},
    {id:555,en:"divorce",ja:"離婚する",ex:"The couple decided to get a divorce."},
    {id:556,en:"document",ja:"記録する、文書",ex:"He documented every step of the process."},
    {id:557,en:"dominate",ja:"支配する",ex:"Large firms dominate the market."},
    {id:558,en:"donate",ja:"寄付する",ex:"The company donated money to the charity."},
    {id:559,en:"double",ja:"2倍にする",ex:"Sales have doubled over the last year."},
    {id:560,en:"doubt",ja:"疑う",ex:"I doubt if he will come to the party."},
    {id:561,en:"download",ja:"ダウンロードする",ex:"You can download the app for free."},
    {id:562,en:"draft",ja:"下書きする",ex:"She is drafting a new proposal."},
    {id:563,en:"drag",ja:"引きずる",ex:"Don't drag the chairs across the floor."},
    {id:564,en:"drain",ja:"排出する",ex:"The water drained away slowly."},
    {id:565,en:"draw",ja:"描く、引く、引き出す",ex:"The event drew a large crowd."},
    {id:566,en:"dream",ja:"夢を見る",ex:"I dream of traveling around the world."},
    {id:567,en:"dress",ja:"服を着る",ex:"You should dress formally for the interview."},
    {id:568,en:"drift",ja:"漂う、流される",ex:"The boat drifted out to sea."},
    {id:569,en:"drill",ja:"穴を開ける、訓練",ex:"The workers are drilling for oil."},
    {id:570,en:"drink",ja:"飲む",ex:"Would you like something to drink?"},
    {id:571,en:"drive",ja:"運転する",ex:"It takes an hour to drive to the airport."},
    {id:572,en:"drop",ja:"落とす、減少する",ex:"Sales dropped sharply in February."},
    {id:573,en:"dry",ja:"乾かす",ex:"Hang your clothes outside to dry."},
    {id:574,en:"dump",ja:"捨てる",ex:"Illegal dumping is a serious problem."},
    {id:575,en:"duplicate",ja:"複製する",ex:"Can you duplicate this key for me?"},
    {id:576,en:"earn",ja:"稼ぐ",ex:"She earns a good salary as a lawyer."},
    {id:577,en:"ease",ja:"和らげる、容易にする",ex:"The new law will ease the burden on small shops."},
    {id:578,en:"eat",ja:"食べる",ex:"Where shall we eat tonight?"},
    {id:579,en:"echo",ja:"響く、反響する",ex:"His words echoed in the hall."},
    {id:580,en:"economize",ja:"節約する",ex:"We need to economize on electricity."},
    {id:581,en:"edit",ja:"編集する",ex:"He is editing a documentary film."},
    {id:582,en:"educate",ja:"教育する",ex:"The school aims to educate young people."},
    {id:583,en:"effect",ja:"もたらす、効果",ex:"The new policy will effect many changes."},
    {id:584,en:"eject",ja:"取り出す、追い出す",ex:"Press the button to eject the disk."},
    {id:585,en:"elaborate",ja:"詳しく述べる、精巧な",ex:"Could you elaborate on that point?"},
    {id:586,en:"elect",ja:"選出する",ex:"He was elected as the new president."},
    {id:587,en:"elevate",ja:"高める、上げる",ex:"Exercise can elevate your mood."},
    {id:588,en:"eliminate",ja:"取り除く",ex:"We must eliminate all errors from the data."},
    {id:589,en:"embarrass",ja:"恥ずかしい思いをさせる",ex:"I didn't mean to embarrass you."},
    {id:590,en:"embark",ja:"乗り出す",ex:"The firm is about to embark on a new venture."},
    {id:591,en:"embody",ja:"具体化する",ex:"She embodies all the qualities of a leader."},
    {id:592,en:"embrace",ja:"抱きしめる、受け入れる",ex:"We should embrace new technology."},
    {id:593,en:"emerge",ja:"現れる",ex:"The sun emerged from behind the clouds."},
    {id:594,en:"emphasize",ja:"強調する",ex:"The manager emphasized the need for safety."},
    {id:595,en:"employ",ja:"雇う",ex:"The company employs over 500 people."},
    {id:596,en:"empower",ja:"権限を与える",ex:"The course empowers women to lead."},
    {id:597,en:"empty",ja:"空にする",ex:"Please empty your pockets."},
    {id:598,en:"enable",ja:"可能にする",ex:"The software enables us to work faster."},
    {id:599,en:"enact",ja:"制定する",ex:"The government plans to enact the new law."},
    {id:600,en:"encapsulate",ja:"カプセルに包む、要約する",ex:"The report encapsulates our main ideas."},
    {id:601,en:"enclose",ja:"同封する、囲む",ex:"Please find the check enclosed."},
    {id:602,en:"encounter",ja:"遭遇する",ex:"We encountered some problems with the system."},
    {id:603,en:"encourage",ja:"励ます",ex:"My teacher encouraged me to study abroad."},
    {id:604,en:"end",ja:"終わる",ex:"The show ends at 10 PM."},
    {id:605,en:"endanger",ja:"危険にさらす",ex:"Pollution endangers many animal species."},
    {id:606,en:"endorse",ja:"支持する、承認する",ex:"The board voted to endorse the proposal."},
    {id:607,en:"endow",ja:"寄付する、授ける",ex:"The hospital was endowed by a local billionaire."},
    {id:608,en:"endure",ja:"耐える",ex:"She had to endure a long wait."},
    {id:609,en:"enforce",ja:"執行する",ex:"The police enforce the law."},
    {id:610,en:"engage",ja:"従事する、惹きつける",ex:"He is engaged in a new research project."},
    {id:611,en:"engineer",ja:"設計する、巧みに仕組む",ex:"They managed to engineer a deal."},
    {id:612,en:"enhance",ja:"高める",ex:"The upgrade will enhance the performance."},
    {id:613,en:"enjoy",ja:"楽しむ",ex:"I enjoy playing tennis on weekends."},
    {id:614,en:"enlarge",ja:"拡大する",ex:"They plan to enlarge the kitchen."},
    {id:615,en:"enlighten",ja:"啓発する",ex:"Can you enlighten me on this topic?"},
    {id:616,en:"enlist",ja:"協力を得る、入隊する",ex:"We need to enlist more volunteers."},
    {id:617,en:"enquire",ja:"尋ねる",ex:"I called to enquire about the position."},
    {id:618,en:"enrich",ja:"豊かにする",ex:"Travel enriches your life."},
    {id:619,en:"enroll",ja:"登録する、入会する",ex:"You can enroll in the course online."},
    {id:620,en:"ensure",ja:"確実にする",ex:"Please ensure that all windows are closed."},
    {id:621,en:"entail",ja:"伴う、必要とする",ex:"The job entails a lot of travel."},
    {id:622,en:"enter",ja:"入る、入力する",ex:"Enter your password to log in."},
    {id:623,en:"entertain",ja:"楽しませる",ex:"We hired a magician to entertain the kids."},
    {id:624,en:"entitle",ja:"資格を与える",ex:"Membership entitles you to a discount."},
    {id:625,en:"entrust",ja:"任せる",ex:"He entrusted me with his secrets."},
    {id:626,en:"enumerate",ja:"列挙する",ex:"She enumerated the reasons for her choice."},
    {id:627,en:"envision",ja:"思い描く",ex:"They envision a future without pollution."},
    {id:628,en:"equal",ja:"等しい",ex:"Two plus two equals four."},
    {id:629,en:"equip",ja:"備え付ける",ex:"The gym is equipped with modern machines."},
    {id:630,en:"erase",ja:"消す",ex:"You can erase the errors with an eraser."},
    {id:631,en:"erect",ja:"建てる、直立した",ex:"The monument was erected in 1920."},
    {id:632,en:"erode",ja:"腐食する、浸食する",ex:"The cliffs are being eroded by the sea."},
    {id:633,en:"err",ja:"誤る",ex:"To err is human."},
    {id:634,en:"escape",ja:"逃げる",ex:"The prisoner managed to escape."},
    {id:635,en:"establish",ja:"設立する、確立する",ex:"The firm was established in 1950."},
    {id:636,en:"estimate",ja:"見積もる",ex:"The repair cost is estimated at $500."},
    {id:637,en:"evaluate",ja:"評価する",ex:"We need to evaluate the results carefully."},
    {id:638,en:"evaporate",ja:"蒸発する",ex:"The water soon evaporated in the sun."},
    {id:639,en:"evolve",ja:"進化する、発展する",ex:"The company has evolved over the years."},
    {id:640,en:"exacerbate",ja:"悪化させる",ex:"His comments only exacerbated the situation."},
    {id:641,en:"exaggerate",ja:"誇張する",ex:"Don't exaggerate the importance of the event."},
    {id:642,en:"examine",ja:"調査する、検査する",ex:"The doctor examined the patient."},
    {id:643,en:"exceed",ja:"超える",ex:"The cost must not exceed the budget."},
    {id:644,en:"exchange",ja:"交換する",ex:"I need to exchange some money."},
    {id:645,en:"excite",ja:"興奮させる",ex:"The news excited everyone in the office."},
    {id:646,en:"exclude",ja:"除外する",ex:"Tax is excluded from the price."},
    {id:647,en:"excuse",ja:"許す、言い訳",ex:"Please excuse my late arrival."},
    {id:648,en:"execute",ja:"実行する、処刑する",ex:"The plan was executed perfectly."},
    {id:649,en:"exemplify",ja:"例証する、良い例となる",ex:"This building exemplifies modern design."},
    {id:650,en:"exempt",ja:"免除する",ex:"Some people are exempt from paying tax."},
    {id:651,en:"exercise",ja:"運動する、行使する",ex:"I exercise at the gym twice a week."},
    {id:652,en:"exert",ja:"行使する、努力する",ex:"He exerted all his influence to win."},
    {id:653,en:"exhale",ja:"息を吐く",ex:"Inhale deeply, then exhale slowly."},
    {id:654,en:"exhaust",ja:"疲れ果てさせる、使い果たす",ex:"The long walk exhausted me."},
    {id:655,en:"exhibit",ja:"展示する",ex:"The museum exhibits ancient artifacts."},
    {id:656,en:"exile",ja:"追放する",ex:"He was exiled for his political views."},
    {id:657,en:"exist",ja:"存在する",ex:"Do you believe that ghosts exist?"},
    {id:658,en:"expand",ja:"拡大する",ex:"The firm plans to expand its business."},
    {id:659,en:"expect",ja:"期待する、予想する",ex:"I expect to finish the work by Friday."},
    {id:660,en:"expedite",ja:"早める",ex:"We need to expedite the delivery process."},
    {id:661,en:"expel",ja:"追放する、追い出す",ex:"He was expelled from school for fighting."},
    {id:662,en:"expend",ja:"費やす",ex:"They expend a lot of energy on the project."},
    {id:663,en:"experience",ja:"経験する",ex:"I experienced many difficulties in the job."},
    {id:664,en:"explain",ja:"説明する",ex:"Could you explain this rule to me?"},
    {id:665,en:"explode",ja:"爆発する",ex:"The bomb exploded in the city center."},
    {id:666,en:"exploit",ja:"活用する、搾取する",ex:"We should exploit all our resources."},
    {id:667,en:"explore",ja:"探検する、調査する",ex:"We need to explore all the options."},
    {id:668,en:"export",ja:"輸出する",ex:"The country exports oil and gas."},
    {id:669,en:"expose",ja:"さらす、暴露する",ex:"Don't expose the film to light."},
    {id:670,en:"express",ja:"表現する、急行の",ex:"He expressed his feelings in a letter."},
    {id:671,en:"extend",ja:"延長する、広げる",ex:"The deadline was extended by a week."},
    {id:672,en:"extinguish",ja:"消す",ex:"Firefighters managed to extinguish the fire."},
    {id:673,en:"extract",ja:"引き出す、抽出する",ex:"They extract oil from the ground."},
    {id:674,en:"face",ja:"直面する、顔",ex:"We must face the truth."},
    {id:675,en:"facilitate",ja:"促進する",ex:"Modern tools facilitate communication."},
    {id:676,en:"fade",ja:"色あせる、消えていく",ex:"The colors will fade in the sun."},
    {id:677,en:"fail",ja:"失敗する",ex:"The plan failed due to a lack of money."},
    {id:678,en:"fall",ja:"落ちる",ex:"Rain began to fall steadily."},
    {id:679,en:"falsify",ja:"偽造する",ex:"He was accused of falsifying documents."},
    {id:680,en:"fancy",ja:"想像する、高級な",ex:"I fancy a cup of tea right now."},
    {id:681,en:"fascinate",ja:"魅了する",ex:"Ancient history fascinates me."},
    {id:682,en:"fashion",ja:"作る、流行",ex:"She fashioned a bowl out of clay."},
    {id:683,en:"fasten",ja:"締める",ex:"Please fasten your seatbelt."},
    {id:684,en:"favor",ja:"好む、支持する",ex:"Most people favor the new law."},
    {id:685,en:"fear",ja:"恐れる",ex:"He fears heights."},
    {id:686,en:"feature",ja:"特徴にする、特集する",ex:"The film features several famous actors."},
    {id:687,en:"feed",ja:"与える",ex:"Don't forget to feed the dog."},
    {id:688,en:"feel",ja:"感じる",ex:"I feel very tired today."},
    {id:689,en:"fetch",ja:"取ってくる",ex:"Could you fetch me a glass of water?"},
    {id:690,en:"fight",ja:"戦う",ex:"They are fighting for their rights."},
    {id:691,en:"fill",ja:"満たす",ex:"Please fill the tank with gas."},
    {id:692,en:"filter",ja:"ろ過する",ex:"The water is filtered before bottling."},
    {id:693,en:"finalize",ja:"仕上げる",ex:"We need to finalize the contract."},
    {id:694,en:"finance",ja:"資金を調達する",ex:"The project is financed by the government."},
    {id:695,en:"find",ja:"見つける",ex:"I can't find my keys anywhere."},
    {id:696,en:"finish",ja:"終わらせる",ex:"I'll finish the report by tomorrow."},
    {id:697,en:"fire",ja:"発射する、解雇する、火",ex:"He was fired for being late."},
    {id:698,en:"fit",ja:"合う",ex:"This key doesn't fit the lock."},
    {id:699,en:"fix",ja:"修理する、固定する",ex:"Can you fix my computer?"},
    {id:700,en:"flash",ja:"きらめく、点滅する",ex:"A light started to flash on the panel."},{id:701,en:"flatten",ja:"平らにする",ex:"The storm flattened the wheat fields."},
    {id:702,en:"float",ja:"浮かぶ",ex:"Wood floats on water."},
    {id:703,en:"flood",ja:"氾濫させる、洪水",ex:"The river flooded the entire valley."},
    {id:704,en:"flourish",ja:"繁栄する",ex:"The city flourished as a trade center."},
    {id:705,en:"flow",ja:"流れる",ex:"The river flows into the sea."},
    {id:706,en:"fluctuate",ja:"変動する",ex:"Vegetable prices fluctuate according to the season."},
    {id:707,en:"flush",ja:"（水を）流す、赤らめる",ex:"Please flush the toilet after use."},
    {id:708,en:"fly",ja:"飛ぶ、ハエ",ex:"Birds fly south for the winter."},
    {id:709,en:"focus",ja:"焦点を合わせる",ex:"We need to focus on our core business."},
    {id:710,en:"fold",ja:"折る、畳む",ex:"Fold the paper in half."},
    {id:711,en:"follow",ja:"従う、続く",ex:"Follow the instructions carefully."},
    {id:712,en:"forbid",ja:"禁止する",ex:"Smoking is forbidden in the building."},
    {id:713,en:"forecast",ja:"予測する、予報",ex:"Rain is forecast for tomorrow."},
    {id:714,en:"foresee",ja:"予見する",ex:"It's hard to foresee the future."},
    {id:715,en:"forget",ja:"忘れる",ex:"Don't forget to lock the door."},
    {id:716,en:"forgive",ja:"許す",ex:"Please forgive me for being late."},
    {id:717,en:"form",ja:"形作る、形態",ex:"The students formed a circle."},
    {id:718,en:"formulate",ja:"策定する、明確に述べる",ex:"We are formulating a new strategy."},
    {id:719,en:"foster",ja:"促進する、養育する",ex:"The club aims to foster team spirit."},
    {id:720,en:"found",ja:"設立する、基礎を置く",ex:"The company was founded in 1990."},
    {id:721,en:"frame",ja:"枠にはめる、枠組み",ex:"He framed the diploma and hung it up."},
    {id:722,en:"free",ja:"自由にする、無料の",ex:"The prisoners were finally freed."},
    {id:723,en:"freeze",ja:"凍る、固定する",ex:"Water freezes at 0 degrees Celsius."},
    {id:724,en:"frighten",ja:"怖がらせる",ex:"The loud noise frightened the baby."},
    {id:725,en:"frown",ja:"顔をしかめる",ex:"He frowned at the news."},
    {id:726,en:"fry",ja:"揚げる、炒める",ex:"Fry the onions until brown."},
    {id:727,en:"fulfill",ja:"果たす、満たす",ex:"The product fulfills all our requirements."},
    {id:728,en:"function",ja:"機能する、機能",ex:"The machine is functioning perfectly."},
    {id:729,en:"fund",ja:"資金を提供する",ex:"The project is funded by private donors."},
    {id:730,en:"furnish",ja:"備え付ける、提供する",ex:"The apartment is fully furnished."},
    {id:731,en:"further",ja:"促進する、さらに遠い",ex:"They want to further their education."},
    {id:732,en:"gain",ja:"得る、増す",ex:"The company gained a large market share."},
    {id:733,en:"gather",ja:"集める、集まる",ex:"The kids gathered around the teacher."},
    {id:734,en:"gaze",ja:"見つめる",ex:"She gazed out at the mountains."},
    {id:735,en:"generalize",ja:"一般化する",ex:"It's hard to generalize about young people."},
    {id:736,en:"generate",ja:"生み出す",ex:"The solar panels generate electricity."},
    {id:737,en:"gesture",ja:"身振りをする",ex:"He gestured for me to sit down."},
    {id:738,en:"get",ja:"得る、〜になる",ex:"I need to get some more sleep."},
    {id:739,en:"give",ja:"与える",ex:"Could you give me a hand?"},
    {id:740,en:"glance",ja:"ちらりと見る",ex:"He glanced at his watch."},
    {id:741,en:"glow",ja:"光を放つ",ex:"The embers glowed in the dark."},
    {id:742,en:"go",ja:"行く",ex:"I have to go to work now."},
    {id:743,en:"govern",ja:"統治する、支配する",ex:"The country is governed by a parliament."},
    {id:744,en:"grab",ja:"つかむ",ex:"Let's grab a coffee."},
    {id:745,en:"graduate",ja:"卒業する",ex:"She graduated from college last year."},
    {id:746,en:"grant",ja:"与える、認める",ex:"The bank granted him a loan."},
    {id:747,en:"grasp",ja:"把握する、握る",ex:"I failed to grasp the main point."},
    {id:748,en:"greet",ja:"挨拶する",ex:"The host greeted us at the door."},
    {id:749,en:"grin",ja:"にこっと笑う",ex:"He grinned from ear to ear."},
    {id:750,en:"grind",ja:"粉にひく",ex:"I grind my own coffee beans."},
    {id:751,en:"grip",ja:"しっかり握る",ex:"He gripped the steering wheel tightly."},
    {id:752,en:"grow",ja:"成長する、育てる",ex:"Our business is growing rapidly."},
    {id:753,en:"guarantee",ja:"保証する",ex:"The product is guaranteed for one year."},
    {id:754,en:"guard",ja:"守る",ex:"The soldiers are guarding the palace."},
    {id:755,en:"guess",ja:"推測する",ex:"Can you guess how old he is?"},
    {id:756,en:"guide",ja:"案内する",ex:"The signs will guide you to the exit."},
    {id:757,en:"halt",ja:"止める、止まる",ex:"Production was halted by the strike."},
    {id:758,en:"hammer",ja:"ハンマーで打つ",ex:"He hammered the nail into the wood."},
    {id:759,en:"handle",ja:"扱う、取っ手",ex:"Please handle the glass with care."},
    {id:760,en:"hang",ja:"吊るす、掛ける",ex:"Hang your coat on the hook."},
    {id:761,en:"happen",ja:"起こる",ex:"What happened to your car?"},
    {id:762,en:"harass",ja:"嫌がらせをする",ex:"The company has a zero-tolerance policy on harassment."},
    {id:763,en:"harm",ja:"害する",ex:"Smoking harms your health."},
    {id:764,en:"harvest",ja:"収穫する",ex:"Farmers are busy harvesting wheat."},
    {id:765,en:"hasten",ja:"急がせる",ex:"The treatment helped hasten his recovery."},
    {id:766,en:"hate",ja:"嫌う",ex:"I hate getting up early."},
    {id:767,en:"have",ja:"持っている",ex:"Do you have any brothers or sisters?"},
    {id:768,en:"head",ja:"向かう、頭",ex:"Where are you heading?"},
    {id:769,en:"heal",ja:"治る",ex:"The wound took a long time to heal."},
    {id:770,en:"hear",ja:"聞く、聞こえる",ex:"I can hear someone calling."},
    {id:771,en:"heat",ja:"加熱する",ex:"Heat the soup before serving."},
    {id:772,en:"heave",ja:"持ち上げる、投げる",ex:"They heaved the heavy box onto the truck."},
    {id:773,en:"heighten",ja:"高める",ex:"The news heightened our tension."},
    {id:774,en:"help",ja:"助ける",ex:"Can you help me with this box?"},
    {id:775,en:"hesitate",ja:"ためらう",ex:"Don't hesitate to contact us."},
    {id:776,en:"hide",ja:"隠す",ex:"The clouds hid the moon."},
    {id:777,en:"highlight",ja:"強調する",ex:"The report highlights the main issues."},
    {id:778,en:"hinder",ja:"妨げる",ex:"The heavy snow hindered our progress."},
    {id:779,en:"hint",ja:"ヒントを与える",ex:"He hinted that he might resign."},
    {id:780,en:"hire",ja:"雇う、借りる",ex:"The firm plans to hire more staff."},
    {id:781,en:"hit",ja:"打つ、当たる",ex:"The car hit a tree."},
    {id:782,en:"hold",ja:"持つ、開催する",ex:"The meeting will be held in the hall."},
    {id:783,en:"honor",ja:"称える、名誉",ex:"The award honors her achievements."},
    {id:784,en:"hope",ja:"望む",ex:"I hope you have a nice trip."},
    {id:785,en:"host",ja:"主催する",ex:"Japan hosted the Olympic Games."},
    {id:786,en:"house",ja:"収容する、家",ex:"The museum houses ancient art."},
    {id:787,en:"hug",ja:"抱きしめる",ex:"They hugged each other at the airport."},
    {id:788,en:"humiliate",ja:"恥をかかせる",ex:"I was humiliated by his comments."},
    {id:789,en:"hunt",ja:"狩る、探す",ex:"The cat is hunting for mice."},
    {id:790,en:"hurry",ja:"急ぐ",ex:"We need to hurry or we'll be late."},
    {id:791,en:"hurt",ja:"傷つける",ex:"My leg hurts a lot."},
    {id:792,en:"hypothesize",ja:"仮説を立てる",ex:"Scientists hypothesize that the climate is changing."},
    {id:793,en:"identify",ja:"特定する",ex:"Can you identify the man in the photo?"},
    {id:794,en:"ignore",ja:"無視する",ex:"She ignored my advice."},
    {id:795,en:"illuminate",ja:"照らす、解明する",ex:"The stars illuminated the night sky."},
    {id:796,en:"illustrate",ja:"説明する、挿絵を入れる",ex:"The chart illustrates the sales growth."},
    {id:797,en:"imagine",ja:"想像する",ex:"Imagine living on the moon."},
    {id:798,en:"imitate",ja:"真似る",ex:"He can imitate his boss perfectly."},
    {id:799,en:"immerse",ja:"浸す、没頭させる",ex:"She immersed herself in her work."},
    {id:800,en:"impact",ja:"影響を与える",ex:"The new tax will impact everyone."},
    {id:801,en:"impede",ja:"邪魔する、遅らせる",ex:"Traffic was impeded by the construction."},
    {id:802,en:"implement",ja:"実行する",ex:"We will implement the plan next week."},
    {id:803,en:"implicate",ja:"巻き込む、含意する",ex:"He was implicated in the scandal."},
    {id:804,en:"imply",ja:"暗示する",ex:"What do you mean to imply?"},
    {id:805,en:"import",ja:"輸入する",ex:"Japan imports most of its oil."},
    {id:806,en:"impose",ja:"課す、押しつける",ex:"The government imposed a new tax."},
    {id:807,en:"impress",ja:"印象づける",ex:"His performance impressed the judges."},
    {id:808,en:"imprison",ja:"投獄する",ex:"He was imprisoned for ten years."},
    {id:809,en:"improve",ja:"改善する",ex:"We are working to improve our service."},
    {id:810,en:"inaugurate",ja:"就任させる、開始する",ex:"The new president was inaugurated today."},
    {id:811,en:"include",ja:"含む",ex:"Does the price include breakfast?"},
    {id:812,en:"incorporate",ja:"組み込む",ex:"We incorporated your ideas into the plan."},
    {id:813,en:"increase",ja:"増える、増やす",ex:"Sales increased by 20% last year."},
    {id:814,en:"incur",ja:"負う、被る",ex:"The company incurred heavy losses."},
    {id:815,en:"indicate",ja:"示す",ex:"The signs indicate the way to the exit."},
    {id:816,en:"induce",ja:"誘発する、説得する",ex:"The drug can induce sleep."},
    {id:817,en:"indulge",ja:"ふける、甘やかす",ex:"I like to indulge in a good book."},
    {id:818,en:"infect",ja:"感染させる",ex:"The computer was infected with a virus."},
    {id:819,en:"infer",ja:"推論する",ex:"What can we infer from these facts?"},
    {id:820,en:"influence",ja:"影響を与える",ex:"The weather influences our mood."},
    {id:821,en:"inform",ja:"知らせる",ex:"Please inform us of any changes."},
    {id:822,en:"infringe",ja:"侵害する",ex:"The product infringes our patent."},
    {id:823,en:"infuse",ja:"注入する、吹き込む",ex:"The news infused everyone with hope."},
    {id:824,en:"inherit",ja:"相続する",ex:"She inherited a fortune from her aunt."},
    {id:825,en:"inhibit",ja:"抑制する",ex:"Cold weather inhibits plant growth."},
    {id:826,en:"initiate",ja:"開始する",ex:"The company initiated a new project."},
    {id:827,en:"inject",ja:"注射する、投入する",ex:"The government injected money into the economy."},
    {id:828,en:"injure",ja:"傷つける",ex:"He injured his leg while playing soccer."},
    {id:829,en:"innovate",ja:"革新する",ex:"The firm continues to innovate."},
    {id:830,en:"input",ja:"入力する",ex:"Input your password to continue."},
    {id:831,en:"inquire",ja:"尋ねる",ex:"I called to inquire about the room."},
    {id:832,en:"insert",ja:"挿入する",ex:"Insert the disk into the drive."},
    {id:833,en:"insist",ja:"主張する",ex:"He insisted on paying for lunch."},
    {id:834,en:"inspect",ja:"検査する",ex:"A technician came to inspect the boiler."},
    {id:835,en:"inspire",ja:"鼓舞する、着想を与える",ex:"Her courage inspired everyone."},
    {id:836,en:"install",ja:"設置する、インストールする",ex:"We installed a new air conditioner."},
    {id:837,en:"instigate",ja:"扇動する、開始する",ex:"He was accused of instigating the strike."},
    {id:838,en:"institute",ja:"制定する、開始する",ex:"The school instituted a new rule."},
    {id:839,en:"instruct",ja:"指示する、教える",ex:"She instructed me to wait here."},
    {id:840,en:"insulate",ja:"絶縁する、断熱する",ex:"The house is well insulated."},
    {id:841,en:"insult",ja:"侮辱する",ex:"I didn't mean to insult you."},
    {id:842,en:"insure",ja:"保険をかける",ex:"Is your house insured against fire?"},
    {id:843,en:"integrate",ja:"統合する",ex:"The new system will integrate all the data."},
    {id:844,en:"intend",ja:"意図する",ex:"I intend to finish this today."},
    {id:845,en:"interact",ja:"相互に作用する",ex:"Teachers and students interact in class."},
    {id:846,en:"interfere",ja:"干渉する、邪魔する",ex:"Don't interfere in my business."},
    {id:847,en:"interpret",ja:"解釈する、通訳する",ex:"How do you interpret this text?"},
    {id:848,en:"interrupt",ja:"中断させる、遮る",ex:"Sorry to interrupt, but there's a phone call."},
    {id:849,en:"intervene",ja:"介入する",ex:"The UN intervened to stop the war."},
    {id:850,en:"interview",ja:"面接する",ex:"We are interviewing candidates today."},
    {id:851,en:"introduce",ja:"紹介する、導入する",ex:"Allow me to introduce my colleague."},
    {id:852,en:"intrude",ja:"侵入する、邪魔する",ex:"I'm sorry to intrude on your privacy."},
    {id:853,en:"invade",ja:"侵略する",ex:"The army invaded the neighboring country."},
    {id:854,en:"invalidate",ja:"無効にする",ex:"A mistake will invalidate the contract."},
    {id:855,en:"invent",ja:"発明する",ex:"Who invented the telephone?"},
    {id:856,en:"invest",ja:"投資する",ex:"You should invest in some stocks."},
    {id:857,en:"investigate",ja:"調査する",ex:"The police are investigating the crime."},
    {id:858,en:"invite",ja:"招待する",ex:"They invited us to their party."},
    {id:859,en:"invoke",ja:"呼びかける、発動する",ex:"He invoked his right to remain silent."},
    {id:860,en:"involve",ja:"含む、巻き込む",ex:"The job involves a lot of traveling."},
    {id:861,en:"iron",ja:"アイロンをかける、鉄",ex:"I need to iron my shirt."},
    {id:862,en:"isolate",ja:"隔離する",ex:"The island is isolated from the mainland."},
    {id:863,en:"issue",ja:"発行する、出す、問題",ex:"The bank issued a new credit card."},
    {id:864,en:"itemize",ja:"項目別にする",ex:"Please itemize your expenses."},
    {id:865,en:"join",ja:"参加する、つなぐ",ex:"Would you like to join us for dinner?"},
    {id:866,en:"joke",ja:"冗談を言う",ex:"He's always joking about his age."},
    {id:867,en:"judge",ja:"判断する、裁判官",ex:"Don't judge a book by its cover."},
    {id:868,en:"jump",ja:"飛ぶ",ex:"The dog jumped over the fence."},
    {id:869,en:"justify",ja:"正当化する",ex:"How can you justify such a high cost?"},
    {id:870,en:"keep",ja:"保つ、飼う",ex:"Please keep the room clean."},
    {id:871,en:"kick",ja:"蹴る",ex:"He kicked the ball into the goal."},
    {id:872,en:"kill",ja:"殺す",ex:"Pollution kills many fish every year."},
    {id:873,en:"kiss",ja:"キスする",ex:"She kissed her baby on the forehead."},
    {id:874,en:"kneel",ja:"ひざまずく",ex:"He knelt down to tie his shoelace."},
    {id:875,en:"knit",ja:"編む",ex:"My grandmother is knitting a sweater."},
    {id:876,en:"knock",ja:"叩く",ex:"Someone is knocking at the door."},
    {id:877,en:"know",ja:"知っている",ex:"Do you know where the station is?"},
    {id:878,en:"label",ja:"ラベルを貼る",ex:"Make sure to label each box clearly."},
    {id:879,en:"lack",ja:"欠いている",ex:"The team lacks experience."},
    {id:880,en:"land",ja:"着陸する、土地",ex:"The plane landed safely at Narita."},
    {id:881,en:"last",ja:"続く、最後の",ex:"The meeting lasted for three hours."},
    {id:882,en:"laugh",ja:"笑う",ex:"Everyone laughed at his joke."},
    {id:883,en:"launch",ja:"開始する、打ち上げる",ex:"The company launched a new product."},
    {id:884,en:"lay",ja:"置く、横たえる",ex:"She laid the baby in the crib."},
    {id:885,en:"lead",ja:"導く、リードする",ex:"This road leads to the city center."},
    {id:886,en:"leak",ja:"漏れる",ex:"The roof is leaking water."},
    {id:887,en:"lean",ja:"寄りかかる",ex:"Don't lean against the glass door."},
    {id:888,en:"leap",ja:"跳ぶ",ex:"The cat leaped onto the table."},
    {id:889,en:"learn",ja:"学ぶ",ex:"I want to learn how to play guitar."},
    {id:890,en:"lease",ja:"賃貸する",ex:"We leased a new office in Tokyo."},
    {id:891,en:"leave",ja:"去る、残す",ex:"I'll leave the office at 6 PM."},
    {id:892,en:"lecture",ja:"講義する",ex:"He lectures on history at the college."},
    {id:893,en:"lend",ja:"貸す",ex:"Can you lend me $10?"},
    {id:894,en:"lengthen",ja:"長くする",ex:"The days begin to lengthen in spring."},
    {id:895,en:"lessen",ja:"減らす",ex:"This medicine will lessen the pain."},
    {id:896,en:"let",ja:"させる",ex:"Let me know if you need any help."},
    {id:897,en:"level",ja:"平らにする、水準",ex:"They leveled the ground for the house."},
    {id:898,en:"levy",ja:"課す、徴収する",ex:"A tax is levied on tobacco products."},
    {id:899,en:"liberate",ja:"解放する",ex:"The army liberated the city."},
    {id:900,en:"license",ja:"免許を与える、認可する",ex:"The software is licensed for three users."},
    {id:901,en:"lie",ja:"嘘をつく、横たわる",ex:"Don't lie to me."},
    {id:902,en:"lift",ja:"持ち上げる",ex:"Can you help me lift this box?"},
    {id:903,en:"light",ja:"明かりをつける、軽い",ex:"He lit a candle in the dark."},
    {id:904,en:"like",ja:"好む",ex:"I like traveling to new places."},
    {id:905,en:"limit",ja:"制限する",ex:"We need to limit our spending."},
    {id:906,en:"line",ja:"並べる、線",ex:"Trees line the street."},
    {id:907,en:"link",ja:"つなぐ",ex:"The two systems are linked together."},
    {id:908,en:"liquidate",ja:"解散する、清算する",ex:"The company was forced to liquidate."},
    {id:909,en:"list",ja:"リストにする",ex:"Please list the items you need."},
    {id:910,en:"listen",ja:"聞く",ex:"Listen to what I'm saying."},
    {id:911,en:"live",ja:"住む、生きる",ex:"Where do you live?"},
    {id:912,en:"load",ja:"積む、読み込む",ex:"The workers are loading the truck."},
    {id:913,en:"loan",ja:"貸し出す",ex:"The bank loaned him $5,000."},
    {id:914,en:"locate",ja:"位置づける、見つける",ex:"The shop is located near the station."},
    {id:915,en:"lock",ja:"鍵をかける",ex:"Don't forget to lock the door."},
    {id:916,en:"log",ja:"ログを取る、記録する",ex:"The system logs every user action."},
    {id:917,en:"look",ja:"見る",ex:"Look at the beautiful sunset."},
    {id:918,en:"loose",ja:"解き放つ、ゆるい",ex:"The dog broke loose from its chain."},
    {id:919,en:"lose",ja:"失う、負ける",ex:"I lost my wallet on the bus."},
    {id:920,en:"love",ja:"愛する",ex:"She loves her family very much."},
    {id:921,en:"lower",ja:"下げる",ex:"Please lower the volume."},
    {id:922,en:"lurk",ja:"潜む",ex:"Danger lurks in the shadows."},
    {id:923,en:"magnify",ja:"拡大する",ex:"A microscope magnifies small objects."},
    {id:924,en:"mail",ja:"郵送する",ex:"I mailed the letter yesterday."},
    {id:925,en:"maintain",ja:"維持する",ex:"It's important to maintain your health."},
    {id:926,en:"make",ja:"作る",ex:"He made a delicious cake."},
    {id:927,en:"manage",ja:"管理する、どうにか〜する",ex:"I managed to catch the last train."},
    {id:928,en:"manifest",ja:"明らかにする、示す",ex:"The symptoms manifest after three days."},
    {id:929,en:"manipulate",ja:"操る",ex:"He knows how to manipulate people."},
    {id:930,en:"manufacture",ja:"製造する",ex:"The firm manufactures car parts."},
    {id:931,en:"map",ja:"地図を描く、計画する",ex:"We mapped out the entire project."},
    {id:932,en:"march",ja:"行進する",ex:"Soldiers marched through the city."},
    {id:933,en:"mark",ja:"印をつける",ex:"Mark the correct answer with a cross."},
    {id:934,en:"market",ja:"売り出す",ex:"The product is marketed worldwide."},
    {id:935,en:"marry",ja:"結婚する",ex:"They got married last June."},
    {id:936,en:"marshal",ja:"整列させる、集める",ex:"He marshaled his arguments for the debate."},
    {id:937,en:"master",ja:"習得する",ex:"She mastered the art of bread making."},
    {id:938,en:"match",ja:"合う、対抗する",ex:"This tie matches your shirt."},
    {id:939,en:"materialize",ja:"具体化する、現れる",ex:"Our plans failed to materialize."},
    {id:940,en:"matter",ja:"重要である",ex:"It doesn't matter what you wear."},
    {id:941,en:"mature",ja:"熟す、成熟する",ex:"The wine needs to mature for five years."},
    {id:942,en:"mean",ja:"意味する",ex:"What does this word mean?"},
    {id:943,en:"measure",ja:"測る、基準",ex:"Measure the length of the table."},
    {id:944,en:"mediate",ja:"仲裁する",ex:"The UN tried to mediate the conflict."},
    {id:945,en:"meet",ja:"会う、満たす",ex:"The product meets all safety standards."},
    {id:946,en:"melt",ja:"溶ける",ex:"The snow melted in the sun."},
    {id:947,en:"memorize",ja:"暗記する",ex:"You need to memorize these words."},
    {id:948,en:"mend",ja:"直す",ex:"I need to mend my socks."},
    {id:949,en:"mention",ja:"言及する",ex:"He didn't mention anything about it."},
    {id:950,en:"merge",ja:"合併する",ex:"The two companies decided to merge."},
    {id:951,en:"merit",ja:"値する、長所",ex:"The proposal merits careful consideration."},
    {id:952,en:"mind",ja:"気にする、精神",ex:"Do you mind if I open the window?"},
    {id:953,en:"minimize",ja:"最小限にする",ex:"We should minimize our waste."},
    {id:954,en:"mirror",ja:"反映する、鏡",ex:"The lake mirrored the mountains."},
    {id:955,en:"mislead",ja:"誤解させる",ex:"The advertisement is misleading."},
    {id:956,en:"miss",ja:"逃す、寂しく思う",ex:"I missed the last train."},
    {id:957,en:"mistake",ja:"間違える",ex:"I mistook him for his brother."},
    {id:958,en:"misunderstand",ja:"誤解する",ex:"I think you misunderstood me."},
    {id:959,en:"mitigate",ja:"和らげる、軽減する",ex:"The new law will mitigate the problem."},
    {id:960,en:"mix",ja:"混ぜる",ex:"Mix the flour and water together."},
    {id:961,en:"mobilize",ja:"動員する",ex:"The troops were mobilized for war."},
    {id:962,en:"mock",ja:"あざける",ex:"He mocked my idea."},
    {id:963,en:"model",ja:"手本にする、モデル",ex:"The school is modeled after a university."},
    {id:964,en:"moderate",ja:"和らげる、適度な",ex:"The weather is moderate today."},
    {id:965,en:"modernize",ja:"現代化する",ex:"They are modernizing the factory."},
    {id:966,en:"modify",ja:"修正する",ex:"We need to modify the design."},
    {id:967,en:"moisturize",ja:"湿らせる",ex:"This cream moisturizes your skin."},
    {id:968,en:"mold",ja:"形作る、型",ex:"The clay was molded into a vase."},
    {id:969,en:"monitor",ja:"監視する",ex:"The machine monitors your heartbeat."},
    {id:970,en:"motivate",ja:"動機づける",ex:"A good teacher motivates students."},
    {id:971,en:"mount",ja:"登る、据え付ける",ex:"They mounted the camera on the wall."},
    {id:972,en:"mourn",ja:"悼む",ex:"The nation mourned the king's death."},
    {id:973,en:"move",ja:"動く、感動させる",ex:"We are moving to a new house."},
    {id:974,en:"multiply",ja:"増やす、掛ける",ex:"Three multiplied by four is twelve."},
    {id:975,en:"murmur",ja:"つぶやく",ex:"He murmured something under his breath."},
    {id:976,en:"name",ja:"名前をつける、名指す",ex:"They named the baby after his father."},
    {id:977,en:"narrate",ja:"語る",ex:"The film is narrated by a famous actor."},
    {id:978,en:"navigate",ja:"航行する、操縦する",ex:"The pilot navigated the ship into port."},
    {id:979,en:"near",ja:"近づく、近い",ex:"The work is nearing completion."},
    {id:980,en:"necessitate",ja:"必要とする",ex:"The project necessitates a lot of money."},
    {id:981,en:"need",ja:"必要とする",ex:"I need some advice."},
    {id:982,en:"neglect",ja:"怠る、無視する",ex:"Don't neglect your duties."},
    {id:983,en:"negotiate",ja:"交渉する",ex:"We are negotiating a new contract."},
    {id:984,en:"neutralize",ja:"無効化する、中和する",ex:"The chemical was neutralized with water."},
    {id:985,en:"nod",ja:"うなずく",ex:"He nodded his head in agreement."},
    {id:986,en:"nominate",ja:"指名する",ex:"He was nominated for an Oscar."},
    {id:987,en:"normalize",ja:"正常化する",ex:"Relations between the two countries normalized."},
    {id:988,en:"note",ja:"気づく、メモする",ex:"Please note that the office is closed."},
    {id:989,en:"notice",ja:"気づく、通知",ex:"I noticed a small error in the report."},
    {id:990,en:"notify",ja:"通知する",ex:"Please notify us of your change of address."},
    {id:991,en:"nourish",ja:"養う",ex:"Plants are nourished by the sun and rain."},
    {id:992,en:"nurture",ja:"育てる",ex:"The club aims to nurture young talent."},
    {id:993,en:"obey",ja:"従う",ex:"You must obey the law."},
    {id:994,en:"object",ja:"反対する、物体",ex:"Many people object to the new tax."},
    {id:995,en:"oblige",ja:"強いる、恩義を施す",ex:"I'm obliged to you for your help."},
    {id:996,en:"observe",ja:"観察する、遵守する",ex:"The scientists observed the animals."},
    {id:997,en:"obstruct",ja:"塞ぐ、妨害する",ex:"Fallen trees obstructed the road."},
    {id:998,en:"obtain",ja:"得る",ex:"You can obtain the form at the desk."},
    {id:999,en:"occupy",ja:"占める",ex:"Reading occupies most of his time."},
    {id:1000,en:"occur",ja:"起こる、浮かぶ",ex:"The accident occurred at 10 PM."}
];